import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  docs: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home',
    },
    {
      type: 'category',
      label: 'Foundations',
      //link: { type: 'doc', id: 'foundations/index' },
      link: {
      type: 'generated-index',
      slug: '/foundations',
      title: 'Foundations Overview',
      description: 'Basic theory and conceptual background needed for DFT and QE.',
      },
      items: [
        {type: 'autogenerated', dirName: 'foundations'}
      ],
    },
    {
      type: 'category',
      label: 'Quantum ESPRESSO',
      //link: { type: 'doc', id: 'qe/index' },
      link: {
        type: 'generated-index',
        slug: '/qe',
        title: 'Quantum ESPRESSO',
        description:
          'Standard workflows for relax, SCF, NSCF, band structure and DOS calculations.',
      },
      items: [
        {type: 'autogenerated', dirName: 'qe'}
      ],
    },
    {
      type: 'category',
      label: 'Softwares',
      //link: { type: 'doc', id: 'softwares/index' },
      link: {
        type: 'generated-index',
        slug: '/softwares',
        title: 'Other relevant softwares',
        description:
          'Visualization and post-processing tools frequently used together with Quantum ESPRESSO.',
      },
      items: [
        {type: 'autogenerated', dirName: 'softwares'}
      ],
    },
    {
      type: 'category',
      label: 'HPC',
      //link: { type: 'doc', id: 'hpc/index' },
      link: {
        type: 'generated-index',
        slug: '/hpc',
        title: 'High-performance computing',
        description:
          'Notes on using HPC resources, job submission, storage, and performance tuning.',
      },
      items: [
        {type: 'autogenerated', dirName: 'hpc'}
      ],
    },
  ],

};

export default sidebars;
