import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  docs: [
    {
      type: 'category',
      label: 'Foundations',
      link: { type: 'doc', id: 'foundations/index' },
      items: ['foundations/his'],
    },
    {
      type: 'category',
      label: 'Quantum ESPRESSO',
      link: { type: 'doc', id: 'qe/index' },
      items: [
        'qe/scf',
        'qe/geo_opt',
        'qe/bands',
      ],
    },
    {
      type: 'category',
      label: 'Softwares',
      link: { type: 'doc', id: 'softwares/index' },
      items: [
        'softwares/vesta',
        'softwares/xcrysden',
      ],
    },
    {
      type: 'category',
      label: 'HPC',
      link: { type: 'doc', id: 'hpc/index' },
      items: [
        'hpc/HEC',
      ],
    },
  ],

};

export default sidebars;
